# Generated by Django 4.2.4 on 2023-08-11 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20230811_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('AddressID', models.AutoField(primary_key=True, serialize=False)),
                ('Street', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Province', models.CharField(max_length=100)),
                ('ZIPCode', models.CharField(max_length=20)),
                ('Country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('AssignmentID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=100)),
                ('AddressID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.address')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('StatusID', models.AutoField(primary_key=True, serialize=False)),
                ('EstimatedArrivalTime', models.DateTimeField()),
                ('ActualArrivalTime', models.DateTimeField()),
                ('DepartedTime', models.DateTimeField()),
                ('Status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateTimeField()),
                ('OrderConfirmation', models.CharField(max_length=50)),
                ('OrderPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Category', models.CharField(max_length=50)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('RoleID', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(choices=[('Supervisor', 'Supervisor'), ('Admin', 'Admin'), ('Driver', 'Driver')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('RouteID', models.AutoField(primary_key=True, serialize=False)),
                ('Origin', models.CharField(max_length=100)),
                ('Destination', models.CharField(max_length=100)),
                ('Distance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('VehicleID', models.AutoField(primary_key=True, serialize=False)),
                ('RegistrationNumber', models.CharField(max_length=20)),
                ('Make', models.CharField(max_length=100)),
                ('Model', models.CharField(max_length=100)),
                ('Capacity', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=100)),
                ('PasswordHash', models.CharField(max_length=128)),
                ('FullName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.role')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('ShipmentID', models.AutoField(primary_key=True, serialize=False)),
                ('AssignmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.assignment')),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.order')),
                ('RouteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.route')),
                ('StatusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.deliverystatus')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('PaymentStatus', models.CharField(max_length=50)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentDate', models.DateTimeField()),
                ('PaymentMethod', models.CharField(max_length=50)),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.order')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('DriverID', models.AutoField(primary_key=True, serialize=False)),
                ('DriverName', models.CharField(max_length=100)),
                ('MobileNumber', models.CharField(max_length=20)),
                ('LicenseNumber', models.CharField(max_length=50)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AddressID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.address')),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.role')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='DriverID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.driver'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='VehicleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.vehicle'),
        ),
    ]
